"""test

Revision ID: 481720caecbe
Revises: 7972a23eaea8
Create Date: 2020-12-11 20:45:01.380303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481720caecbe'
down_revision = '7972a23eaea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
